<?xml version="1.0"?>
<!-- Este archivo corresponde al primer diseño del robot solver
    para la simulacion y lanzamiento de pruebas de ejecucion,
    junto al funcionamiento del robot real.
-->
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <!-- Seccion para creacion de propiedades de links -->
    <xacro:property name="chassis_length" value="0.3920"/>
    <xacro:property name="chassis_height" value="0.3045"/>
    <xacro:property name="chassis_width" value="0.2500"/>
    <!-- Seccion de valores de medidas de ruedas -->
    <xacro:property name="wheel_radius" value="0.07"/>
    <xacro:property name="wheel_thickness" value="0.047"/>
    <xacro:property name="wheel_offset_x" value="0.226"/>
    <xacro:property name="wheel_offset_y" value="0.175"/>
    <xacro:property name="wheel_offset_z" value="0.01"/>

    <!-- Esta seccion corresponde al color y descripcion de materiales-->
    <material name = "blue">
        <color rgba = "${3/255} ${111/255} ${183/255} 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="red">
        <color rgba="${255/255} ${99/255} ${71/255} 1"/>
    </material>

    <material name="green">
        <color rgba="${0/255} ${198/255} ${66/255} 1"/>
    </material>
    <!-- Seccion de base link -->
    <link name="base_link"></link>

    <!-- Seccion de creacion de link de chasis -->
    <!-- Primero se crea la articulacion (joint) -->
    <joint name = "chassis_joint" type = "fixed">
        <parent link = "base_link"/>
        <child link = "chassis"/>
        <origin xyz = "${-chassis_length/2} 0 0"/>
    </joint>

    <link name="chassis">
        <visual>
            <origin xyz="${chassis_length/2} 0 ${chassis_width/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_height} ${chassis_width}"/>
            </geometry>
            <material name="blue"/>
        </visual>
    </link>

    <!-- Seccion de diseño de ruedas, donde se tiene en cuenta la transmision entre las 2 -->
    <!-- Seccion de ruedas de la izquierda -->
    <joint name = "left_wheel_joint" type = "continuous">
        <parent link="base_link"/>
        <child link="left_wheel_front"/>
        <origin xyz="0 ${wheel_offset_y} 0" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1"/>
    </joint>

    <link name="left_wheel_front">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="green"/>
        </visual>
    </link>
</robot>